# Generated by Django 3.2.25 on 2025-07-22 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peliculas', '0002_auto_20250605_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='autor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to=settings.AUTH_USER_MODEL),
        ),
    ]
