# Generated by Django 3.2.25 on 2025-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_pelicula_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
