# Generated by Django 3.2.25 on 2025-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250327_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
