# Generated by Django 3.2.25 on 2025-06-22 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='hora_creacion',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
